security:
    password_hashers:
        App\Entity\Employe: 'auto'

    providers:
        employe_provider:
            entity:
                class: App\Entity\Employe
                property: username

    firewalls:
        main:
            provider: employe_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_paie_index
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true  # Replaces csrf_token_generator
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
            logout:
                path: /logout  # This is the route for logging out
                target: app_login  # After logout, the user is redirected to the login page
                # You can also configure custom behavior, like redirecting to a different URL

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/directeur, roles: ROLE_DIRECTEUR }
        - { path: ^/facturation, roles: ROLE_FACTURATION }
        - { path: ^/charges, roles: ROLE_CHARGES }
        - { path: ^/ouvrier, roles: ROLE_OUVRIER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Low cost for testing
                time_cost: 3 # Low time cost for testing
                memory_cost: 10 # Low memory cost for testing
